version: '3.5'
#To rebuild images you must use `docker-compose build` or `docker-compose up --build`
services:
    backend:
        container_name: fairy_client_backend
        build:
            context: ./packages/backend
        ports:
            - '8000:8000'
    frontend:
        container_name: fairy_client_frontend
        build:
            context: ./packages/frontend
        ports:
            - '3000:3000'
        depends_on:
            - backend
